In [1]:
### Importing libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv(r'R:\HuB\ESPERANTO\Data_Science\MachineLearningEndToEndProject\RegressionModel\DiamondPricePrediction\notebook\data\gemstone_processed.csv')

In [4]:
df

        carat  depth  table  price  cut  color  clarity
0        1.52   62.2   58.0  13619    2      5        5
1        2.03   62.0   58.0  13387    3      1        7
2        0.70   61.2   57.0   2772    1      4        4
3        0.32   61.6   56.0    666    1      4        4
4        1.70   62.6   59.0  14453    2      4        5
...       ...    ...    ...    ...  ...    ...      ...
193568   0.31   61.1   56.0   1130    1      7        3
193569   0.70   60.3   58.0   2874    2      4        3
193570   0.73   63.1   57.0   3036    3      5        6
193571   0.34   62.9   55.0    681    3      7        6
193572   0.71   60.8   64.0   2258    4      6        7

[193573 rows x 7 columns]

In [5]:
X = df.drop('price',axis=1)

In [6]:
y = df['price']

In [7]:
X

        carat  depth  table  cut  color  clarity
0        1.52   62.2   58.0    2      5        5
1        2.03   62.0   58.0    3      1        7
2        0.70   61.2   57.0    1      4        4
3        0.32   61.6   56.0    1      4        4
4        1.70   62.6   59.0    2      4        5
...       ...    ...    ...  ...    ...      ...
193568   0.31   61.1   56.0    1      7        3
193569   0.70   60.3   58.0    2      4        3
193570   0.73   63.1   57.0    3      5        6
193571   0.34   62.9   55.0    3      7        6
193572   0.71   60.8   64.0    4      6        7

[193573 rows x 6 columns]

In [8]:
y

0         13619
1         13387
2          2772
3           666
4         14453
          ...
193568     1130
193569     2874
193570     3036
193571      681
193572     2258
Name: price, Length: 193573, dtype: int64

In [9]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
## pipeline
from sklearn.pipeline import Pipeline   
from sklearn.compose import ColumnTransformer

In [19]:
num_cols = X.columns[X.dtypes != 'object']

In [20]:
num_cols

Index(['carat', 'depth', 'table', 'cut', 'color', 'clarity'], dtype='object')

In [ ]:
### Numerical Pipeline 
pipeline = Pipeline(
steps= [
        ('imputer',SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ]
)




preprocessor = ColumnTransformer([
    ('numerical_pipe',pipeline,num_cols)
  
])

In [22]:
### Train-Test-Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=30 , random_state=30)

In [23]:
X_train = pd.DataFrame(preprocessor.fit_transform(X_train), columns=preprocessor.get_feature_names_out())
X_test = pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [24]:
X_train

,numerical_pipe__carat,numerical_pipe__depth,numerical_pipe__table,numerical_pipe__cut,numerical_pipe__color,numerical_pipe__clarity
0,-0.952403,-0.666241,-0.639753,-0.872926,1.550242,-0.016566
1,0.085068,0.073391,0.402572,-0.872926,0.934118,-0.682440
2,1.554818,-0.019063,1.444896,0.132979,-1.530381,0.649308
3,-0.174300,-0.851149,-0.118590,-0.872926,-1.530381,-0.016566
4,-0.195914,0.535661,-0.639753,-0.872926,-0.298132,0.649308
...,...,...,...,...,...,...
193538,-1.038859,-0.019063,-0.639753,-0.872926,0.934118,0.649308
193539,0.992855,0.165845,-0.639753,-0.872926,-0.298132,1.315182
193540,0.452506,1.552655,-0.639753,2.144787,-0.298132,0.649308
193541,0.668645,-1.775689,1.444896,-0.872926,-0.298132,-0.682440
193542,0.257980,0.813023,-0.118590,-0.872926,-0.298132,0.649308

In [25]:
X_test

,numerical_pipe__carat,numerical_pipe__depth,numerical_pipe__table,numerical_pipe__cut,numerical_pipe__color,numerical_pipe__clarity
0,-0.563351,-0.943603,-0.639753,0.132979,0.934118,-0.016566
1,-0.174300,0.997931,-0.118590,1.138883,-0.914256,0.649308
2,-1.060473,0.258299,-0.118590,-0.872926,-0.914256,-2.680062
3,0.971241,-0.203971,1.966059,0.132979,-0.298132,-0.016566
4,-0.930789,-1.313419,0.402572,0.132979,0.934118,-0.682440
5,-0.195914,-4.364402,2.487221,2.144787,0.317993,-0.016566
6,0.538962,0.535661,-0.118590,-0.872926,-0.914256,0.649308
7,1.554818,-0.296425,0.402572,0.132979,0.934118,-0.682440
8,0.301208,1.182839,-0.118590,2.144787,1.550242,0.649308
9,1.987098,0.997931,1.966059,1.138883,-2.146506,-0.016566
10,0.517348,0.813023,-0.639753,-0.872926,-0.298132,-2.014188
11,0.452506,-2.053051,2.487221,0.132979,-2.146506,1.315182
12,1.554818,-2.977592,1.444896,3.150692,-2.146506,1.315182
13,0.538962,-0.019063,-0.639753,-0.872926,-0.298132,1.315182
14,0.474120,1.645109,-0.639753,1.138883,0.317993,-0.016566
15,0.474120,0.443207,0.402572,0.132979,-0.298132,-0.016566
16,2.613903,-2.237960,1.966059,0.132979,-2.146506,0.649308
17,0.668645,-1.868143,1.444896,-0.872926,-0.298132,-0.016566
18,-0.844333,0.443207,-0.118590,-0.872926,-0.298132,-0.016566
19,0.603803,0.165845,-0.639753,-0.872926,0.934118,0.649308
20,2.613903,1.552655,1.444896,1.138883,-0.298132,1.315182
21,-1.038859,0.165845,-1.682077,-0.872926,-0.914256,-0.682440
22,1.036083,0.350753,0.402572,0.132979,-0.298132,0.649308
23,-0.844333,-1.220965,1.444896,0.132979,0.934118,-0.016566
24,-0.930789,-0.388879,-0.118590,-0.872926,1.550242,-0.016566
25,2.635517,0.073391,0.402572,1.138883,-1.530381,-0.682440
26,1.576432,0.165845,-0.118590,0.132979,-0.298132,0.649308
27,1.533204,-0.851149,0.923734,1.138883,0.317993,-0.016566
28,1.554818,-0.851149,-0.118590,-0.872926,1.550242,1.315182
29,1.533204,1.737563,-1.160915,2.144787,1.550242,1.315182

In [26]:
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [27]:
def evalute_model(true,predicted):
    mae = mean_absolute_error(true,predicted)
    mse = mean_squared_error(true,predicted)
    r2_scored = r2_score(true,predicted)
    return mae , mse ,r2_scored

In [32]:
models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'ElasticNet':ElasticNet()
}



trained_model_list=[]
model_list=[]
r2_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    y_pred=model.predict(X_test)

    mae, rmse, r2_scored=evalute_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_scored*100)

    r2_list.append(r2_scored)
    
    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 2400367.9056275687
MAE: 1011.1855948811046
R2 score 90.01102039738265
===================================


Lasso
Model Training Performance
RMSE: 2404708.36480935
MAE: 1011.7215675738092
R2 score 89.99295785033262
===================================


Ridge
Model Training Performance
RMSE: 2400412.3128433875
MAE: 1011.1890808756308
R2 score 90.01083559955563
===================================


ElasticNet
Model Training Performance
RMSE: 7676598.232054291
MAE: 1872.431221318001
R2 score 68.05432076570338
===================================

In [ ]:
di = {
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'ElasticNet':ElasticNet()
}
for i in list(di):  #di.keys():
    print(i)

LinearRegression
Lasso
Ridge
ElasticNet

In [31]:
list(di.values())

[LinearRegression(), Lasso(), Ridge(), ElasticNet()]